/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class HabitLogSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'done', 'habitId', 'id', 'updatedAt'] as const
  $columns = HabitLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare done: boolean | null
  @column()
  declare habitId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HabitSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = HabitSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TodoSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'dueDate', 'filePath', 'id', 'isCompleted', 'priority', 'title', 'updatedAt'] as const
  $columns = TodoSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare filePath: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCompleted: boolean | null
  @column()
  declare priority: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
